# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: 'tutum/mongodb'
    restart: always
    environment:
      MONGODB_DATABASE: "mydatabase"
      MONGODB_USER: "user" 
      MONGODB_PASS: "pass"
    ports:
      - '27017:27017'
